_common: !include "common.yaml"

verbatim: 
  cabal-version: 2.4
name:                scanner
version:             0.1.0.0
github:              nini-faroux/scanner
author:              nini
license: MPL-2.0
license-file:
  - "LICENSE"
maintainer:          example@example.com
copyright:           2020 Author name here

extra-source-files:
- README.md
- ChangeLog.md

<<: *common-options

library:
  source-dirs: src

executables:
  scanner-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - scanner
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  scanner-test:
    <<: *common-tests
    main:                Spec.hs
